# Pr치ctica 06 - Ejercicio 1

Este notebook contiene la carga, limpieza, transformaci칩n y exportaci칩n de datos a MySQL usando un archivo CSV.

In [25]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine, text

## 1. Importaci칩n de Datos

In [23]:
df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")
df.head()

C:\Users\esauv\AppData\Local\Temp\ipykernel_22676\595041609.py:1: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,NaN,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,NaN,NaN,POINT (-72.879115982 41.773452988)

## 2. Limpieza de Datos

In [11]:
df.info()
df = df.dropna(axis=1, how='all')  # Elimina columnas completamente vac칤as
df = df.dropna(how='any')  # Elimina filas con al menos un NaN
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 560 entries, 674 to 1097517
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   serial_number     560 non-null    int64
 1   list_year         560 non-null    int64
 2   date_recorded     560 non-null    object
 3   town              560 non-null    object
 4   address           560 non-null    object
 5   assessed_value    560 non-null    float64
 6   sale_amount       560 non-null    float64
 7   sales_ratio       560 non-null    float64
 8   property_type     560 non-null    object
 9   residential_type  560 non-null    object
 10  non_use_code      560 non-null    object
 11  assessor_remarks  560 non-null    object
 12  opm_remarks       560 non-null    object
 13  location          560 non-null    object
dtypes: float64(3), int64(2), object(9)
memory usage: 65.6+ KB

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,assessor_remarks,opm_remarks,location
674,210296,2021,07/06/2022,Berlin,355 RESERVOIR RD,172300.0,240000.0,0.717917,Residential,Single Family,25 - Other,OTHER,TWO SALES IN ONE DAY - SEE #210295,POINT (-72.804847962 41.612923994)
715,210197,2021,11/30/2021,Fairfield,125 VESPER STREET,264320.0,334000.0,0.791377,Residential,Single Family,25 - Other,POSSIBLE DURESS,PER MLS SLOPING ISSUES ON 2ND FLOOR. ENGINEERS...,POINT (-73.234403987 41.179839983)
1381,211177,2021,06/28/2022,Danbury,55 MILL PLAIN RD 13-1,146600.0,285000.0,0.514386,Residential,Condo,25 - Other,D15004-80,DUPLICATE ENTRY - ALSO SEE #211176,POINT (-73.502786995 41.391933021)
1438,210856,2021,04/13/2022,Danbury,60 NABBY RD 78,151600.0,350000.0,0.433143,Residential,Condo,25 - Other,L08054-78,DUPLICATE ENTRY - ALSO SEE #210855,POINT (-73.421529975 41.429339988)
2066,210140,2021,09/15/2022,East Granby,143-145 NORTH MAIN STREET,130600.0,75000.0,1.741333,Residential,Two Family,07 - Change in Property,"PP TOO LOW, RATIO TOO HIGH",POOR CONDITION PER MLS - ASSESSMENT REDUCED TO...,POINT (-72.720844025 41.963067982)

## 3. Transformaci칩n de Datos

In [17]:
if 'sale_date' in df.columns:
    df['sale_date'] = pd.to_datetime(df['sale_date'], errors='coerce')
if 'sale_date' in df.columns:
    df['sale_year'] = df['sale_date'].dt.year
df.head()

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,assessor_remarks,opm_remarks,location
674,210296,2021,07/06/2022,Berlin,355 RESERVOIR RD,172300.0,240000.0,0.717917,Residential,Single Family,25 - Other,OTHER,TWO SALES IN ONE DAY - SEE #210295,POINT (-72.804847962 41.612923994)
715,210197,2021,11/30/2021,Fairfield,125 VESPER STREET,264320.0,334000.0,0.791377,Residential,Single Family,25 - Other,POSSIBLE DURESS,PER MLS SLOPING ISSUES ON 2ND FLOOR. ENGINEERS...,POINT (-73.234403987 41.179839983)
1381,211177,2021,06/28/2022,Danbury,55 MILL PLAIN RD 13-1,146600.0,285000.0,0.514386,Residential,Condo,25 - Other,D15004-80,DUPLICATE ENTRY - ALSO SEE #211176,POINT (-73.502786995 41.391933021)
1438,210856,2021,04/13/2022,Danbury,60 NABBY RD 78,151600.0,350000.0,0.433143,Residential,Condo,25 - Other,L08054-78,DUPLICATE ENTRY - ALSO SEE #210855,POINT (-73.421529975 41.429339988)
2066,210140,2021,09/15/2022,East Granby,143-145 NORTH MAIN STREET,130600.0,75000.0,1.741333,Residential,Two Family,07 - Change in Property,"PP TOO LOW, RATIO TOO HIGH",POOR CONDITION PER MLS - ASSESSMENT REDUCED TO...,POINT (-72.720844025 41.963067982)

## 4. Exportar Datos a una Tabla Temporal de SQL (MySQL)

In [26]:
user = 'root'
password = 'vargas2030'
host = 'localhost'
database = 'bd_realstate'

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")
df.to_sql(name='tabla_temporal_ventas', con=engine, if_exists='replace', index=False)

print("Exportaci칩n exitosa.")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No se puede establecer una conexi칩n ya que el equipo de destino deneg칩 expresamente dicha conexi칩n)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)